### ISSUE TITLE
1.7.10 Config option to not give Book

### ISSUE THREAD

**Issue by nmarshall23** [oitsjustjose/V-Tweaks#10]
I'm putting together a modpack and I don't want players to spawn with the book.

In the pack not all of V-Tweak's, tweaks will be enabled. So there is no need to taunt players.

**Comment by oitsjustjose** [comment]
I've got to be honest - I'm probably not going to look into this. 

I haven't modded for 1.7.10 in almost 6 months; I don't have a development environment around for it anymore, and quite frankly, while I understand how this is a desired feature - it's just a book. You can let your players figure it out themselves I suppose.

Seeing as how this isn't a critical, game-breaking bug, I can't validate supporting _**three**_ different Minecraft versions all at once. It's just not something I can handle while also trying to jam in summer classes in college. Sorry.

**Comment by nmarshall23** [comment]
Is there branch for the 1.7.10 version? I might be able to find the spare time to add the option myself.

**Comment by oitsjustjose** [comment]
[This](http://minecraft.curseforge.com/projects/v-tweaks/files/2271255) is the most recent archive of the source I have for 1.7.10 - note that the latest released version of V-Tweaks for 1.7.10 was actually newer than this though (sorry for inconsistency, I really and truly thought that nobody would care about 1.7.10 support by now.. I mean, come on... it's pretty much a dead version). 

If you want to fiddle-fart with it, you're free to! Sorry I can't be of more help - I deleted my entire dev workspace for 1.7.10 (including source code I was keeping around local-only) back in like.... December.. when nobody seemed to ever be asking for more 1.7.10 content.

**Comment by nmarshall23** [comment]
I'd say, 1.7.10 will be around for at least the next 6 months. Good quality mods take time to update. 

Anyhow, I'd take a look at peek, look like this has the Challenger Mobs, in it. I might fork that.. 

One more thing, your repo has the LGPL and GPL in it but curseforge lists the mod as MIT. Those are very different Licensing..

Thanks for getting back to me, I hope in that future you use `git tag` for releases.
