### ISSUE TITLE
Right click to harvest crops feature affecting Mangrove Propagule

### ISSUE THREAD

**Issue by ArkVeil** [oitsjustjose/V-Tweaks#105]
It is not possible to directly apply bonemeal to planted propagule's because V-Tweak's right click to harvest feature is overriding bonemeal priority. You just get stuck attempting to "harvest" the propagule but it does not drop.

**Comment by oitsjustjose** [comment]
Forgot to mention I fixed this a while ago! Thank you for the report!!
