### ISSUE TITLE
Can't access the configuration in game

### ISSUE THREAD

**Issue by dazcdxfezc** [oitsjustjose/V-Tweaks#106]
I'm currently on forge 1.20.1 - 47.1.0 and I can't access the menu to configure the mod. I don't know if that's not how we're suppsosed to do it but in my control settings I don't have any key that'll open a configuration menu.
![a](https://github.com/oitsjustjose/V-Tweaks/assets/139223456/07606d4a-8a26-4f2c-b6ff-e64772d7bc6d)

**Comment by oitsjustjose** [comment]
Yeah this won't be supported by me - you have to write your entirely own GUI code to make this work, and I just don't have time. I use the standard Forge Configs so I'd suggest [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) when it gets ported to 1.20. Sorry for the nofix response :/

**Comment by dazcdxfezc** [comment]
ok no problem, thanks for the answer
