### ISSUE TITLE
concrete powder conversion not working

### ISSUE THREAD

**Issue by nevercamearound** [oitsjustjose/V-Tweaks#107]
in the config, the fluid conversion is turned on but when I throw the concrete powder in water it does nothing

**Comment by oitsjustjose** [comment]
What version is this on?

**Comment by nevercamearound** [comment]
1.20.1

**Comment by oitsjustjose** [comment]
Thanks a ton- fixed via [d7589dc](https://github.com/oitsjustjose/V-Tweaks/commit/d7589dc025cfcbceeaabe019886442993d450728) and 4.0.8 :)
