### ISSUE TITLE
[enhancement] [1.8] [1.9] reduced/configurable Xp requirement for books

### ISSUE THREAD

**Issue by swyrl** [oitsjustjose/V-Tweaks#11]
Given that typical enchanting and anvil uses require only a few levels in 1.8+, I feel it would be appropriate to reduce the XP requirement for making enchanted books from 30 to 10 (still more expensive than conventional enchanting by about 3x), or to make it configurable so users can adjust it themselves. (especially considering that it is impossible to obtain the enchantments through conventional means.)

**Comment by oitsjustjose** [comment]
I like this idea a lot.

I'll work on it and have a release for 1.8.9 and 1.9.4 with it in the next day or two :D

**Comment by oitsjustjose** [comment]
Updates for V-Tweaks on 1.9.4 and 1.8.9 are on CurseForge now including this change :D 

Thanks for the suggestion! :heart:
