### ISSUE TITLE
metadata drops for challenger mobs?

### ISSUE THREAD

**Issue by 4rz0** [oitsjustjose/V-Tweaks#13]
Is it possible to have challenger mobs drop items that require metadata, for example the alternative minecraft planks or colored wood?
I tried it with `minecraft:wool:1`, but they always drop the 0 variant.

**Comment by oitsjustjose** [comment]
That's because to specify Metadata you've also got to specify quantity. In other words, you should do this:

`minecraft:wool:1*1`, where the *1 is specifying you want 1 to drop.

Just tested this in my dev environment and it works this way. Sorry for the inconvenience, but the config file does say this too, in case you forget!

**Comment by 4rz0** [comment]
Oh wow, I totally didn't see that line :I
I'm sorry, this is perfect!
Thanks :D

**Comment by oitsjustjose** [comment]
No problem! I just hope that not too many people decide they need NBT support, because I don't know how that'll work out...

**Comment by 4rz0** [comment]
Ok, I managed to play with the settings you suggested, but I still have a problem.
I want the mods to drop IC2 iridium shards.
For that, I use `ic2:misc_resource:2*1`, but the mobs drop ash, which is metadata ic2:misc_resource with metadata 0.

**Comment by oitsjustjose** [comment]
I have a feeling that's because IC2 also uses NBT for its blocks and ingots now. Unfortunately I can't really fix this without overhauling the drop system in a way that I simply won't be doing. Sorry man, might be worth looking into non-IC2 drops.

**Comment by oitsjustjose** [comment]
So I just tried a few things myself as well, and I've updated V-Tweaks to (hopefully) fix this. I ran into a similar bug on my own as well with Lapis, so hopefully I've fixed that problem!

**Comment by 4rz0** [comment]
I tried testing that version (1.4.9.3).
Curse says it's available for MC 1.9, but the mod says it needs 1.10.2.

**Comment by oitsjustjose** [comment]
Re-Uploaded on Curse to fix this (sorry). Should be an active download soon (it'll be the same V-Tweaks version)

**Comment by 4rz0** [comment]
Thanks!
By the way, the initial fix works!
Stuff drops as intended now :D
