### ISSUE TITLE
[Suggestion] Config option to disable the "Seems like this is your first time running V-Tweaks in this world!" message

### ISSUE THREAD

**Issue by TheRandomLabs** [oitsjustjose/V-Tweaks#17]

**Comment by oitsjustjose** [comment]
I mean, I can add a config for this but you literally ONLY see it once per world. How often are you resetting worlds?!

**Comment by TheRandomLabs** [comment]
I don't mind if you can't add the config option, but I'm resetting worlds quite often because I'm doing testing.

**Comment by WesCook** [comment]
I'd have to agree with @TheRandomLabs on this one.  I get it from a dev perspective, but as a modpack author it feels like a failing to have any messages shown in chat (eg. update messages, debug info).  I spend a lot of time trying to prevent these messages, so it's problematic when there's no way to disable them.

**Comment by WesCook** [comment]
Thanks Jose!
