### ISSUE TITLE
Challenger Mob drop crash [1.3]

### ISSUE THREAD

**Issue by dirtyfargo** [oitsjustjose/V-Tweaks#2]
Description: Once in a while, when a challenger mob dies, the game crashes. It doesn't seem to matter which type of challenger mob, and it doesn't happen every time.
Crash-Report: https://gist.github.com/dirtyfargo/041e9bd4a8ed56a4f562
Version: 1.3  for 1.7.10
Forge Version: 10.13.4.1614
Unrelated note: I'm getting a lot of the challenger mobs suffocating in walls on spawn, not sure if this is an issue on your end though as I'm playing in a decently sized modpack. Oh and I should maybe also mention that the hypermending enchantment actually seems to give me XP instead of take it away when I enchant a tool in the Enchanting Plus Advanced Enchanting Table, but again not sure if this is an issue on your end :)

**Comment by oitsjustjose** [comment]
Fixed this in 1.8.8, haven't had a chance to do so for 1.7.10, but I've also had this issue. I'll work on the fix now :)

On your unrelated notes: challenger mobs suffocating shouldn't be on my end... that I know of. All my code does is takes an already occurring mob spawn and modify the mob spawned after spawning it. So I can't imagine what it is.

Hypermending is not meant to be acquired via any form of enchanting table, so if it can be, then that's on Enchanting Plus. I make my code pretty straight forward for that: I set the min and max level range both to 0 - meaning it's acquirable. If the Enchanting Plus developer doesn't acknowledge that then.. that's poor planning ;P

**Comment by dirtyfargo** [comment]
Alright awesome thanks! :)
Yeah, as for the suffocating mobs, I have a bunch of mods that alter terrain generation, so maybe the problem is somewhere there, not sure :P
Enchanting Plus I just found out has a cfg option to blacklist enchantment ids, so I can fix the issue there :)

**Comment by oitsjustjose** [comment]
Bug has been fixed, grab the update [here](http://minecraft.curseforge.com/projects/v-tweaks/files/2271253) :)
