### ISSUE TITLE
Encountered an unexpected exception

### ISSUE THREAD

**Issue by bookerthegeek** [oitsjustjose/V-Tweaks#22]
[Gist report][1]
Server crash after a few minutes after loading world. 

Can provide [Curse Import File][2] for instance.

Edit: Most likely the result of removing all loot for the challenger mobs.

[1]:https://gist.github.com/bookerthegeek/3b72553e892d9f7b6e7c59912e769fda
[2]:https://github.com/MyM-ModpackTeam/RageQuit/raw/master/CurseDevImport/Rage%20Quit-DEV.zip

**Comment by oitsjustjose** [comment]
Thanks for letting me know, I've been wanting to work on them anyways so I went ahead and did a decently-large overhaul

**Comment by bookerthegeek** [comment]
Thank you.
