### ISSUE TITLE
[Suggestion] Lava Loss Protection - Blocks list / tweak

### ISSUE THREAD

**Issue by TDarkShadow** [oitsjustjose/V-Tweaks#24]
Instead of only Obsidian and Chisel's Basalt, which I btw very appreciate of you of adding in,
would it be possible to have a config or list option where you can add blocks so they have the same protection?

Otherwise, would it be possible to provide the same protection to blocks that have the same harvest level as Obsidian? (things you can only mine with a Diamond tool)
I know in vanilla this would be Obsidian anyway, but some mods, like Cobalt and Ardite Ore from Tinker's Construct, require a diamond (or higher) tool.

**Comment by oitsjustjose** [comment]
Good idea, it'll be a little while before I'll really have a chance to release it but it's been implemented (I went with a config list, since block hardness means this wouldn't work with Chisel Basalt)
