### ISSUE TITLE
[Suggestion] Step Boost Improvements

### ISSUE THREAD

**Issue by WesCook** [oitsjustjose/V-Tweaks#25]
I really like how the smooth step boost is added as an enchantment, as it's a nice upgrade to the vanilla Auto-Jump feature.  Though I've two suggestions which I think would improve it.

* Holding Crouch should cancel the step up action, similar to how it prevents falling off blocks.  Botania and other step up mods use this convention.
* It currently doesn't play well with Auto-Jump on.  I believe Step Boost should take precedence over Auto-Jump, but not require it be disabled altogether.

**Comment by oitsjustjose** [comment]
Holding crouch is done.

The auto-jump thing is another thing entirely. You bring a good point, but I'm not sure how I'll implement it. Will look further into it next week!

**Comment by WesCook** [comment]
Awesome response time!  Much thanks.  :)

Regarding the second point, I know [StepupFixer](https://minecraft.curseforge.com/projects/stepupfixer) works with Auto-Jump.  You could take a look at their approach and see if it's compatible.  (Licensed under GPLv3)

https://github.com/Aroma1997/StepupFix/blob/master/src/main/java/aroma1997/stepupfix/StepupHooks.java

**Comment by oitsjustjose** [comment]
Sure, I knew how it was done, I was just more curious as to how I'd implement it (i.e. would I override autojump or would autojump override me?).

Thanks for the suggestions!

**Comment by oitsjustjose** [comment]
Finished up and I'll be releasing 1.4.10.0 sometime this evening!

**Comment by WesCook** [comment]
Awesome, thanks very much for the speedy response!

**Comment by WesCook** [comment]
Looks like this was reverted.  Were there issues in trying to make them work together?  Understandable if so.

**Comment by oitsjustjose** [comment]
Yeah, unfortunately there's just not a lot I can *safely* do, since it's a client-side setting. I had a release where the setting was just forceably turned *off*, but of course a server running this code would naturally be very unhappy.

After a few hours of playing around with various implementations which might be more friendly to the idea of keeping it "client only", I gave up after none worked. Sorry - most people keep it completely off anyways.

**Comment by WesCook** [comment]
That's fair.  Thanks for your consideration regardless.
