### ISSUE TITLE
1.11.2 Bug: Pyro Creeper gives permanent fire resistance

### ISSUE THREAD

**Issue by Tetrajak** [oitsjustjose/V-Tweaks#30]
As the title says, the pyro creeper special mobs give you (the player) permanent fire resistance (no timer on effect). Perhaps it should instead set you on fire?

**Comment by oitsjustjose** [comment]
Hmmm.... this is quite possibly a derp on my end. _When_ does it give you this effect? When it explodes? Just curious so I can reproduce :)

**Comment by Tetrajak** [comment]
Ah, my friend who I share a server with says it happened with other special type creepers as well, and only when they were killed (but not just by players, it happened when creepers killed special creepers too).

**Comment by oitsjustjose** [comment]
Interesting.. so do you have other mods installed? I just looked through my code, and I can't see why this would be happening...

**Comment by oitsjustjose** [comment]
So... funny story.

It's vanilla.

Tested in a completely vanilla instance. If you splash a creeper with a potion and then they explode, the potion effect they had when they exploded temporarily turns into a lingering potion in that area. Going to "fix" this by specifically _not_ giving creepers the effect; it was just for burnables anyways.

**Comment by Tetrajak** [comment]
Hah, that is amusing, glad you were able to find the cause, and I look forward to the next update!
