### ISSUE TITLE
Autosmelt + Fortune on Axe for trees

### ISSUE THREAD

**Issue by ReportBot9009** [oitsjustjose/V-Tweaks#31]
Hello,

I just saw your post on /r/feedthebeast and  had to try this mod out! Really great things! 

I have a heavily modded pack that is tweaked and fixed, with many mods added and deleted from FTB Beyond 1.10.2 so it is a breeding ground for strange bugs.

Anyway, the autosmelt + fortune for axes on trees is not working properly. The autosmelt + fortune on pickaxes and ore is working just fine. Not sure what is going on or what I could do to show you. Here is a picture. I've tried all manner of enchant combinations and changing the enchant ID # etc. Nothing seems to work. Everything else in the mod is working just fine.

Here is a pic!: http://imgur.com/a/GDOfE

Thanks

**Comment by oitsjustjose** [comment]
So, "fortune-smelt" only works, by default, on ores. There is however a config option for adding other blocks by which fortune + auto-smelt should be applied, and I just tested to confirm that this _will_ work:

![2017-06-01_05 19 19](https://cloud.githubusercontent.com/assets/3887324/26673236/2c3a74de-468a-11e7-8ba7-d3215de38e0d.png)

![2017-06-01_05 19 44](https://cloud.githubusercontent.com/assets/3887324/26673239/2e309336-468a-11e7-88d6-2fa674b1e65a.png)

![2017-06-01_05 19 48](https://cloud.githubusercontent.com/assets/3887324/26673245/3194a062-468a-11e7-9bc3-942e29702c44.png)

![2017-06-01_05 19 50](https://cloud.githubusercontent.com/assets/3887324/26673248/34c69880-468a-11e7-9bc0-82370df62202.png)

![2017-06-01_05 19 54](https://cloud.githubusercontent.com/assets/3887324/26673251/377a4694-468a-11e7-8720-cd903d689d95.png)

**Comment by ReportBot9009** [comment]
Very well then. Thank you :)
