### ISSUE TITLE
FTB Beyond 1.10.2 and Step Boost

### ISSUE THREAD

**Issue by ReportBot9009** [oitsjustjose/V-Tweaks#32]
Hello again.

I am playing FTB Beyond, tweaked with extra mods etc., and Step Boost does not seem to be working. I've applied the enchant using anvils and the enchantment table from Enchanting Plus. It works 99% of the time with the 1% being random. I'll randomly be walking on a cliff jumping up and I'll suddenly walk up one, but that's it. I've figured out if I remove the boots from my armor and place them in my backpack, then put them back on, Step Boost works for 1 block, then stops.

I've also tried changing the ID #. Not sure if that will do anything...

Anyway, if you need more info let me know.

**Comment by oitsjustjose** [comment]
Sorry, been busy lately but should be able to look more closet soon. What version of V-Tweaks are you running?

**Comment by ReportBot9009** [comment]
Hello,

Sorry for the late reply!

Thanks for the update. I'm currently running 1.4.11.1 in FTB Beyond and I'm still having issues with the Step Boost enchant. What happens is, I put the enchant on, get out of the enchant GUI and take my first few steps towards the enchanting table and it auto steps up! Great! I turn around, walk over to some grassy hills and stop at the first block. Nothing. Doesn't work. I go in the menu and check the enchant is still there, come back out of the GUI and walk forward "stepping up" the first block but stop again at the second. Go in the GUI, come back out, and now I'm able to step up the next block but am stopped at the next one. This continues on and on. I have to go into my inventory and come back out to get the enchant to work, otherwise, it just doesn't work or every so often it'll randomly step up a block.
