### ISSUE TITLE
[Suggestion] Special Mobs - Charged Creeper

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/V-Tweaks#33]
Just what it says on the tin; use the special mobs feature to enable the spawning of charged creepers (since potion effect creepers cause trouble with unlimited duration lingering effects).

**Comment by oitsjustjose** [comment]
Hmm, since I fixed the lingering effects a few versions ago I might pass on this. It's a great idea, but since the vanilla method of getting skulls is a delicate balance, I'd hate to really play with that too much. I'll save this idea for later for sure, I like its potential!
