### ISSUE TITLE
[MC 1.12] Beds don't work as sleeping bags

### ISSUE THREAD

**Issue by Xariyl** [oitsjustjose/V-Tweaks#34]
I'm guessing the vanilla changes to beds broke this functionality. Renaming any color bed to "Sleeping Bag" seems to have no effect whatsoever. When right-clicked, the item gets placed on the ground as an ordinary bed. When broken, it has been renamed back to "White Bed" (or whatever respective color the bed is). I've tried White, Black, and Red beds and neither seem to work.

V-Tweaks 1.4.11.1
Minecraft 1.12
Forge 14.21.0.2335

**Comment by oitsjustjose** [comment]
[Sorry if you hadn't noticed](https://github.com/oitsjustjose/V-Tweaks/blob/1.12/changelog.md). 

If it ends up being a big fuss from many others, I might look into it, but they weren't really... _elegant_. I'd love to have the chance to re-do them as a separate item, but I've seen a [certain mod](https://minecraft.curseforge.com/projects/msu-openblocks-stuff) pop up that aims to port the most used features of OpenBlocks, including elevators and sleeping bags... so I'm curious to see where it ends up going!

**Comment by Xariyl** [comment]
Huh... I did miss that in the changelog. Sorry to bother!

I'm following that other mod also, looking forward to having my (pre Ender-Dragon) hang-glider back :)
