### ISSUE TITLE
Question -

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [oitsjustjose/V-Tweaks#35]
Does V-tweaks allow me to blacklist mobs that can be converted into "Pyro -" your mod is currently conflicting with another. 

https://minecraft.curseforge.com/projects/tf2-stuff-mod/issues/10

**Comment by oitsjustjose** [comment]
That should be totally do-able. Give me some time and hopefully by tomorrow I'll have an update for all 3 versions of Minecraft (1.10.2, 1.11.2 and 1.12) adding a Blacklist *list* which you can add entities which will **not** become Challengers. Thanks for pointing this out, this is actually a really obvious feature I should've thought about sooner.

**Comment by EPIICTHUNDERCAT** [comment]
Fantastic! Thank you for a great mod :)
