### ISSUE TITLE
1.12 Disenchanting seem to be borked

### ISSUE THREAD

**Issue by TyreForHyre** [oitsjustjose/V-Tweaks#36]
Howdy there, I was experimenting with disenchanting with the paper + tool feature and I can't seem to get it working. I've tried it in all the various slots of the crafting table and in the player crafting interface; no dice sadly. I've tried it in a separate instance with only Forge 14.21.1.2426 and VTweaks-1.12-1.4.11.3 and still I couldn't seem to get it to work. I've included the FML log just in case it would somehow be helpful or needed: https://pastebin.com/gcqUKrAm

Thanks for taking the time to read this, if there is any other information required I'd be happy to provide it!

**Comment by oitsjustjose** [comment]
I removed that feature a little bit ago with 1.12's new crafting chaos, I'll look into re-implementing it soon :)

**Comment by oitsjustjose** [comment]
Eh, thinking about it there are several other mods which are also disenchanting, so I don't know if yet another mod - doing it in a *very* cheap way, is what packs need.. Probably won't re-add it without serious convincing - but thanks for reminding me to take it off of the website!
