### ISSUE TITLE
Anvils shouldn't be making books

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [oitsjustjose/V-Tweaks#37]
For some, making an enchantment book in an anvil is alright but I do find it to be a little too OP in a vanilla setting that I was trying to put together for a modpack.
Is it possible to have the enchantment books be attainable via enchanting table. If not, then can it be part of the fishing loot or dungeon loot then? Even if I made the xp requirement 100, it'll just be grindy by then, not difficult.

**Comment by oitsjustjose** [comment]
This is mostly fixed in 2.0 - there's hardly any recipes being added via anvil as there were in the 1.x versions..
