### ISSUE TITLE
1.12.1: "Prevent Overworld Witherboss" prevents the boss in both overworld and nether

### ISSUE THREAD

**Issue by Knito58** [oitsjustjose/V-Tweaks#39]
MC 1.12.1, Forge 14.22.02463, V-Tweaks 1.4.11.4, Gamemode SSP

After setting this switch to false the witherboss can be summoned.

**Comment by oitsjustjose** [comment]
That’s because the config says:
`Prevent Overworld Witherboss`

**True** prevents summoning.

**Comment by Knito58** [comment]
And the nether??? It didn't spawn in the nether. That was the problem.

**Comment by Knito58** [comment]
@oitsjustjose: It did not spawn in the NETHER which is *not* Overworld. After setting the switch to false it did spawn in both overworld and nether. Your setting prevents the wither boss also in the nether which is a problem.

**Comment by oitsjustjose** [comment]
Yup, I get it. I'll fix it in a bit :)

**Comment by oitsjustjose** [comment]
Not sure how I missed it actually. Thanks!

**Comment by Knito58** [comment]
Thank you.
