### ISSUE TITLE
Seems to crash with Just Enough Items mod

### ISSUE THREAD

**Issue by WenXin20** [oitsjustjose/V-Tweaks#4]
With an AbstractMethodError

**Comment by oitsjustjose** [comment]
Can I get some details? A crashlog perhaps?

What versions of V-Tweaks and JEI are you running? What version of MC are you running? When are you crashing - at load, world load, etc.?

**Comment by WenXin20** [comment]
I'm using the newest version of your mod in 1.8 with JEI 1.8 of version 1.13.7-134 at minecraft loading screen.

**Comment by WenXin20** [comment]
(https://github.com/oitsjustjose/V-Tweaks/files/93109/crash-2016-01-16_15.50.08-client.txt)

**Comment by oitsjustjose** [comment]
Try [JEI Version 2.14.0.139](http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2273901) - it seems to be working just fine for me:

![2016-01-16_18 57 02](https://cloud.githubusercontent.com/assets/3887324/12375151/2c3fe9ba-bc83-11e5-9b0d-4fd11952d6f0.png)


Looking through the attached crash-log, V-Tweaks shows to have successfully Constructed and Pre-Initialized, whereas JEI and JEI Addons show to have Constructed and Errored.

**Comment by WenXin20** [comment]
Ok, thanks
