### ISSUE TITLE
Texture-less Gold Nuggets

### ISSUE THREAD

**Issue by Shahelion** [oitsjustjose/V-Tweaks#41]
Often when I kill a challenger mob, it drops a single gold nugget textured as a large purple and black checkered cube instead of a nugget. This initially does not stack with normal gold nuggets unless shift-clicked into an inventory that already contains normal nuggets.

I suspect the config line that specifies the chance to drop 15 gold nuggets is instead dropping a nugget with metadata 15. Not sure what it would have to be changed to.

**Comment by oitsjustjose** [comment]
I'm pretty sure I've fixed this already in #27, can you specify which versions of Minecraft, MinecraftForge and V-Tweaks you are using?
