### ISSUE TITLE
Extra Bonemealing not applying to nether wart

### ISSUE THREAD

**Issue by TyreForHyre** [oitsjustjose/V-Tweaks#46]
Neither blaze powder nor bonemeal seem to cause any updates.
Tested in Minecraft 1.12.2
Forge Version 14.23.4.2758
V-Tweaks Version 2.0.0b

**Comment by oitsjustjose** [comment]
Netherwart "bonemealing" was removed in V-Tweaks 2.x - I actually have been spending so much time on Geolosys that I've neglected to update the "wiki" site for it.
