### ISSUE TITLE
Removal of Hypermending enchantment?!

### ISSUE THREAD

**Issue by mahilo3550** [oitsjustjose/V-Tweaks#47]
I don't see the point of removing all those enchantments this mob was known for because they "were weird, useless,  or just didn't flow right with MC or Modded MC." All of those enchantments were not only very useful, but Multifaceted was unique and Hypermending was the entire reason I used this mod. Please at least put Hypermending back into the mod and just have an option in the config to deactivate it. Thanks.

**Comment by oitsjustjose** [comment]
I feel how I feel about them, and that's not changing. I'm sorry. My best suggestion is to play a pre-2.0 version of V-Tweaks which still has them and works perfectly fine. 

The v2.0 update was mostly a purge of features that didn't fit well with other mods, or were duplicate across mods.
