### ISSUE TITLE
[Question] class names crops for easy harvesting

### ISSUE THREAD

**Issue by Pentasis** [oitsjustjose/V-Tweaks#48]
Is there a way to find the class names of a plant/crop? I'm trying to exclude berry bushes from plant mega pack (since they drop themselves with easy harvesting on).

**Comment by oitsjustjose** [comment]
This is something that absolutely needs work on my end. I'll likely switch it from classname (like `net.minecraft.block.BlockCrop`) to `modid:block` to make it easier for users.

**Comment by oitsjustjose** [comment]
In 1.14 this has changed - I'll be backporting this feature to 1.12 shortly.

**Comment by oitsjustjose** [comment]
This should be much more clear to use in 195cb1abea26776bc093ed4b3d0bcb5fe0099f7c
