### ISSUE TITLE
Tweak to make challenger mobs not horrible

### ISSUE THREAD

**Issue by goreae** [oitsjustjose/V-Tweaks#49]
I don't think you're still updating this but on the off chance you do work on this mod again, for the love of god change how challengers' names are applied. Since you're applying it with a name tag, when you kill one, they drop the tag. Because of this your inventory will fill up with nothing but nametags in no time. It's stupidly annoying. I'm pretty sure there's a way to edit a mob's NBT so it displays with a different name. Anything would be better than getting drowned in tags whenever I go hunting.

**Comment by oitsjustjose** [comment]
Uhhh? That's the *only* way to do this. Do you have other mods installed? It sounds like another mod (like CoFH Core?) is causing named mobs to drop their nametags.

**Comment by oitsjustjose** [comment]
https://www.reddit.com/r/feedthebeast/comments/a9hdjp/anyone_know_what_mod_makes_it_so_mobs_with_names/

**Comment by goreae** [comment]
Oh it was cyclic. I'm so sorry I just assumed it was vanilla behavior for some reason. I'm an idiot. Moving on.
