### ISSUE TITLE
Easy harvest

### ISSUE THREAD

**Issue by Avalonzo** [oitsjustjose/V-Tweaks#5]
Hello I'm not sure if it's a bug or intended but... when using easy harvest and holding right click w/ an empty hand you will stop harvesting when something other than the target plant enters the players hand also cannot harvest while holding tools.

**Comment by oitsjustjose** [comment]
It's intended for you to harvest **only** with an empty hand. So yeah, just be sure to have the plant in your inventory and to keep that inventory slot empty ;) I've been trying to work out a way around this, but I haven't had any luck so for the time being I've just left it to require an empty hand.

**Comment by Avalonzo** [comment]
Fair enough i'll just disable it via config as it's rather annoying for a large farm with many varied crops.

**Comment by oitsjustjose** [comment]
Fair enough. Since you've brought it up, I'll start looking into a possible workaround again :)

**Comment by Avalonzo** [comment]
That's very kind of you thank you either way and keep up the amazing work it's really appreciated :)

**Comment by oitsjustjose** [comment]
Just went through and fixed this for you - how quickly do you need an update? I've sent a ton to CurseForge lately, wouldn't mind giving them a break - but if it's important to you to get it soon, I can go ahead and send it over today, otherwise I'll wait til tomorrow :)

**Comment by Avalonzo** [comment]
Send it where whenever you prefer I don't mind waiting if that's what you would prefer to do :)

**Comment by oitsjustjose** [comment]
Update has been sent to CurseForge and should be up shortly! :)

**Comment by Avalonzo** [comment]
You sir are a legend thank you so much :)
