### ISSUE TITLE
Suggestion: More Challenger Mob Configs

### ISSUE THREAD

**Issue by IdrisQe** [oitsjustjose/V-Tweaks#52]
Currently, Challenger Mob configs seem rather limited. We can disable them, blacklist entities, choose loot, and set the rarity of mobs. It'd be nice to be able to configure them some more, perhaps with configurable potion effects (I think they all seem to have Fire Resistance by default? As far as I've seen anyway. Which is a bit of an issue when I'm using the Consecration mod.) and being able to configure the possible names/types/etc. that are allowed to spawn, maybe even having different "tiers" of challenger mobs with different difficulties and rewards.

**Comment by oitsjustjose** [comment]
I might look into this in the future. For now, the 1.14 version of V-Tweaks offers name customization. I'll be backporting this to 1.12 shortly.

**Comment by oitsjustjose** [comment]
For now, I've added the ability to customize mob names via the langfile. I've got some testing to do on this, however.

**Comment by oitsjustjose** [comment]
Forgot to close this, but I think the features I added were as far as I'm going to go, unfortunately. The future is 1.14! :P
