### ISSUE TITLE
Immersive Engineering Durability Tooltips Broken

### ISSUE THREAD

**Issue by IdrisQe** [oitsjustjose/V-Tweaks#53]
I've noticed this primarily with Immersive Engineering so far, but it could affect other mods.
Many items have incorrect durability tooltips when V-Tweaks' tooltips are enabled.
For example, Wire Cutters appear with 0/1 durability always, despite having way more than that.
The same is true with the Engineer's Hammer showing 1/1.
Even weirder, the Engineer's Manual, despite not being a tool and not having durability, shows a tooltip of -2/1 Durability. The Voltmeter will show -1/1. I think it may be picking up item data values and trying to display them as durability or something.

**Comment by oitsjustjose** [comment]
This is a result of how IE, Tinkers, and others use metadata. They store the durability of the tool in custom (non-vanilla-standard) NBT tags that I'd have to manually write out each blacklist for.
