### ISSUE TITLE
Saplings won't plant themself automatically

### ISSUE THREAD

**Issue by iloDys** [oitsjustjose/V-Tweaks#57]
For some reason dropped saplings won't plant themself.
I tried different saplings (vanilla and modded), tried different undergrounds, but they stay as items you can pick up.
Using Forge 28.1.61 and V-Tweaks 3.0.5.

**Comment by oitsjustjose** [comment]
It’s not immediate, it’s when the sapling *would* despawn. Have you tried to let it despawn to see what happens?


________________________________

**Comment by iloDys** [comment]
> Have you tried to let it despawn to see what happens?

Yes, waited the 5min to despawn the sapling. But it just disappears, like it would without the mod. No planted sapling after the despawn. Even tested with a bunch of saplings, but still the same.

I would like to give you any logfiles, but there are no entries in the logfile that would indicate that there is any error.
