### ISSUE TITLE
pre 2.0 fetures 

### ISSUE THREAD

**Issue by EternalOne11** [oitsjustjose/V-Tweaks#59]
could you just realize 1 version that ports a few of the pre 2.0 features? The reason I'm asking is because of step assist and auto smell. I can't really find any vanilla like mods that have those features. Even in 1.12.2 although I just use the last version before 2.0 for that. To be honest I don't really have any attachments to any of the other features removed in 2.0. since hyper mending is op and multifaceted makes other tools kinda useless. This is just a request. I have no problems if the answer is no.  Also, the main reason im asking is because I look for mods that add to vanilla and nothing crazy modded.

**Comment by oitsjustjose** [comment]
I totally understand where you're coming from, but I don't think I'll be doing this.

Autosmelt was a nice feature, but in 1.12 _every other mod_ wanted to add it 😑

Step Boost as a _pain_ to implement and even after implementation, it was **very** broken. I'll explain why:

Step height is just a number -- the default is 0.6, where 1.0 is a full block height and 0.5 is a half slab height. So, if I re-implement the enchantment, then I increase 0.6 by 0.4 to make it 1.0. 

But what if another mod does this?? Then what? I don't want to add 0.4 if your step height is already 1.0, so I may choose *not* to add 0.4. But then if you take them off, how do I know whether or not to subtract 0.4 - and how do I know if you are continuing to get a step boost from some other mod?

Overall the step boost deal is a mess and I try to avoid it.

Sorry though!
