### ISSUE TITLE
StepAssist function in 1.14?

### ISSUE THREAD

**Issue by vhhawk** [oitsjustjose/V-Tweaks#60]
Hello, I installed V-Tweaks because of the StepAssist function shown in the explanatory video. However, it does not seem to function in 1.14, and as best I can tell the last time I see it in the code is in 1.10. Can you include this in 1.14?

**Comment by oitsjustjose** [comment]
See https://github.com/oitsjustjose/V-Tweaks/issues/59#issuecomment-547004138

**Comment by oitsjustjose** [comment]
Oh, also - the website has a filter function that tells you what's still implemented and not, since some things are no longer implemented.

https://oitsjustjose.com/Mods/V-Tweaks 😀
