### ISSUE TITLE
[1.14] Why does the mod messes with damages?

### ISSUE THREAD

**Issue by Insane96** [oitsjustjose/V-Tweaks#61]
When you get damaged by a mob it deals "true damage", ignoring Resistance potion effect. Also when you die you always get the message "<player_name> died" instead of a mob specific message.

**Comment by oitsjustjose** [comment]
I'll try to work on this soon. I modify damage sources with Imperishable and completely forgot about certain aspects; I may in fact remove that functionality altogether so that Imperishable is only for tools.

Thanks for letting me know!

**Comment by oitsjustjose** [comment]
Not sure why I closed this. Re-opening because I've just finished re-working Imperishable for armor to work... well, better.

**Comment by oitsjustjose** [comment]
Ok, now it's fixed. See https://github.com/oitsjustjose/V-Tweaks/commit/279e6ca8d82d134a2c09088fb96b76ea1e542388
