### ISSUE TITLE
More obvious challenger mobs.

### ISSUE THREAD

**Issue by RamenNoodles** [oitsjustjose/V-Tweaks#62]
I've been using this mod for a little over a month now and I was wondering if there would be an easier way to notice challenger mobs without getting close.

Though the only thing I can think of adding the potion particle effect on them.  This might be no different to what a witch would look like when they use potions or the blaze particle effect might interfere since they have smoke particle effects on them.  I think it would be best if you could get the effect that enchanted items. It help a lot when hunting for challenger mobs though.

**Comment by oitsjustjose** [comment]
I could make them glow?

**Comment by RamenNoodles** [comment]
That would make sure easy to spot, but it might be too intrusive since they can be seen through walls.

Unfortunately I don't know what kind of effects you can put on entities to come up with an idea.

**Comment by oitsjustjose** [comment]
Fair... I'll think on it a bit.

**Comment by oitsjustjose** [comment]
I decided to take a note of how Atomic Stryker's Inferno Mobs work, and add particle effects. Unlike inferno mobs, I've decided to set the color based on the challenger mob trait :smile:

**Comment by RamenNoodles** [comment]
Brilliant, don't forget to add options to the config to enable/disable it.

**Comment by oitsjustjose** [comment]
Added config *plus* it follows the Game settings for particles (e.g. all, minimal)

![2019-11-11_13 32 57](https://user-images.githubusercontent.com/3887324/68625532-5fb57b00-04a7-11ea-9bd4-fdc4c0998c4d.png)
![2019-11-11_13 34 19](https://user-images.githubusercontent.com/3887324/68625533-5fb57b00-04a7-11ea-8c17-720e4ece7de7.png)
![2019-11-11_13 34 34](https://user-images.githubusercontent.com/3887324/68625534-5fb57b00-04a7-11ea-8bbb-f627957f637d.png)
![2019-11-11_13 35 57](https://user-images.githubusercontent.com/3887324/68625535-5fb57b00-04a7-11ea-8778-30b250f91d86.png)
![2019-11-11_17 14 50](https://user-images.githubusercontent.com/3887324/68625537-5fb57b00-04a7-11ea-945e-412d685ed92c.png)
![2019-11-11_17 15 25](https://user-images.githubusercontent.com/3887324/68625538-5fb57b00-04a7-11ea-97ea-8553a676ed79.png)
