### ISSUE TITLE
The particle effects spawning without a mob with mega torches.

### ISSUE THREAD

**Issue by RamenNoodles** [oitsjustjose/V-Tweaks#63]
![2019-11-15_22-11-10](https://user-images.githubusercontent.com/4823380/68987255-260da880-07f6-11ea-9389-db81ff37d63a.jpg)

After I put a mega torch down from the torchmaster mod these particle effects would keep spawning making it impossible to load the world.

**Comment by oitsjustjose** [comment]
These particles spawn in so much that it lags the world?!?

**Comment by RamenNoodles** [comment]
Yeah, when I tried to get back into my server I would get a message about not enough ram.  The world seemed to be fine but I just couldn't log back into it.

I should also mention that I'm using version 3.1.0

**Comment by oitsjustjose** [comment]
I just re-wrote the particle tick handler so I'm *really* hoping that fixes this issue, because I can't think of any reason this would still occur. The new system applies particles to all entities on the server, so if the entity doesn't exist it shouldn't work...
