### ISSUE TITLE
half dead mobs 1.15.2

### ISSUE THREAD

**Issue by EternalOne11** [oitsjustjose/V-Tweaks#68]
I think this is on your end But for some reason, I keep getting mobs that don't die and fall over (this is about 1 in 25-100. It is possible its another one of my mods that is causing it in the 1.15.2 version but and easy way to test is to be in creative in a planes biome at night and type /kill @e[type=!player] (this is the kill all entities command besides the player) If you can replicate it then that is the issue I have found.

**Comment by oitsjustjose** [comment]
Can I get a mod list?

**Comment by EternalOne11** [comment]
will grab one.

**Comment by oitsjustjose** [comment]
Closing as I haven't heard back. Let me know if you do end up with the modlist and can repeat this bug, I have no idea what's causing is still.
