### ISSUE TITLE
Vanilla hostile mobs no longer spawn in overworld

### ISSUE THREAD

**Issue by felltablet** [oitsjustjose/V-Tweaks#70]
Title.  Checked all mods, started multiple worlds, this is definitely due to V-Tweaks interfering with the natural spawning of mobs.

**Comment by oitsjustjose** [comment]
It's a feature called "Peaceful Surface";  mobs should spawn on the surface only on new moons. Disable it in the config if you don't like it

**Comment by felltablet** [comment]
Thanks, I was messing with the Y value to no avail.  Changing the option
below works.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
