### ISSUE TITLE
[1.15.2][Despwan Time Adjustment] Un-pickup-able item entity spawn when using /give

### ISSUE THREAD

**Issue by yezhiyi9670** [oitsjustjose/V-Tweaks#71]
If "Despawn Time Adjustment" is enabled, using `/give` will spawn a un-pickup-able item entity even though the item is added to inventory. The item entity can be destroyed by lava/fire or explosions.

This is quite annoying when using command blocks frequently, but I want to extend despawn time to 10min (I know unlimited time will lag the server out).

**Comment by oitsjustjose** [comment]
Yeah this for sure is a weird one. I've experienced it as well *many* times, but I haven't been able to track down the issue myself either. I'll be investigating it here soon and I'll let you know if I find anything!
