### ISSUE TITLE
[1.15.2] Challenger mob config disable not working

### ISSUE THREAD

**Issue by Hexblood** [oitsjustjose/V-Tweaks#73]
Mod Version: 3.1.6
Forge: 31.2.9

Issue: Setting Challenger mob spawning to false in the config does not disable their spawning.

Expected behavior: Challenger mobs to not show up when set to false.

**Comment by oitsjustjose** [comment]
I've been testing this issue out for a few hours and I cannot reproduce this issue. Do you have any extra information regarding this bug?

**Comment by oitsjustjose** [comment]
Closing _for now_ just for my sake, but if this issue comes back up let me know!
