### ISSUE TITLE
[1.15.2] pack.mcmeta pack_format may be incorrect / Enchantment Descriptions aren't working

### ISSUE THREAD

**Issue by HipHopHuman** [oitsjustjose/V-Tweaks#75]
I noticed this in a pack I'm building which uses CoFH Core for enchantment descriptions (which follows the same localization format as the Enchantment Descriptions mod) and the descriptions for V-Tweak's enchantments were not appearing. I normally override this sort of thing with my own resource pack, but for some reason the keys `enchantment.vtweaks.imperishable.desc` and `enchantment.vtweaks.lumbering.desc` are ignored.

I had a little poke around your `1.15` branch and noticed [this line of pack.mcmeta](https://github.com/oitsjustjose/V-Tweaks/blob/1.15/src/main/resources/pack.mcmeta#L4) is using the incorrect `pack_format` version. 

Your version is "4", but the correct `pack_format` version for 1.15 is "5", according to [the official wiki](https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack)

![image](https://user-images.githubusercontent.com/70091260/95011764-525f2d00-0633-11eb-8823-787fc6758c13.png)

**Comment by oitsjustjose** [comment]
That makes sense. Since I don’t add any textures I never really keep up with the version. 

I’ll fix this later today 😊
