### ISSUE TITLE
Hostile mobs spawn (suggestion)

### ISSUE THREAD

**Issue by DamienBrittan** [oitsjustjose/V-Tweaks#76]
Dude , peacefulSurfaceEnabled should be "false" by default ! What is this "vanilla" tweak ? I spent 2 days trying to fix issue with mobs not spawning , and this was all because of this .. i know there's 4 year old video with walkthrough , but when you are trying to make custom modpack with 130+ mods you cannot watch and read all staff about mod itself . I knew this mod is great cuz i played with it at 1.12 but i didn't remember the changes with mobs .  
Edit : just watched the whole video , this shit is not even there ..

**Comment by oitsjustjose** [comment]
Sorry for the inconvenience this caused you, I can agree with changing the default to `false`, but there's a wiki for V-Tweaks at https://mods.oitsjustjose.com/V-Tweaks/

**Comment by DamienBrittan** [comment]
Thanks ! But at curseforge wiki doesn't work . 404 not found . it's probably old link or something

**Comment by DamienBrittan** [comment]
Checked wiki , there's no info about peaceful surface too ;)

**Comment by oitsjustjose** [comment]
Thanks for letting me know about everything. I have updated the wiki link on the CurseForge page to point to the right address, and I just added the Peaceful Surface feature to it!

I'm going to reopen this issue so I remember to adjust the default from `true` to `false`
