### ISSUE TITLE
[1.16.4] Please Restore Autosmelt?

### ISSUE THREAD

**Issue by VaelophisNyx** [oitsjustjose/V-Tweaks#77]
Very, Very few mods include anything like this in 1.16.4, sadly. And some of them that do, dont include one that actually works

If you're worried about "Oh, *another* autosmelt mod" being a concern for people, you could maybe try to make it disableable?

**Comment by oitsjustjose** [comment]
I could do all of this but honestly in the new day and age of data-driven smelting, it's nowhere near as easy to implement as it used to be. For this reason I'm unfortunately going to close this. Thanks for the feedback though! If I have a large amount of free-time in the future I may work on doing just this :smile:
