### ISSUE TITLE
Challenger mob crash with Better Burning mod

### ISSUE THREAD

**Issue by azaquaz** [oitsjustjose/V-Tweaks#79]
As far as I can tell, this crash was caused by an iron golem fighting a "pyro creeper," which I think is a challenger mob from this mod since I can't find a "pyro" affix in the Champions mod. There's no detailed information on challenger mobs I can find on any of this mod's pages, though, so I can't be sure.

Crash: https://pastebin.com/eaizQkMX
Better Burning issue: https://github.com/Darkhax-Minecraft/Better-Burning/issues/6#issue-793780605

**Comment by Darkhax** [comment]
The issue seems to be completely on my end, and has been resolved in a new update.
