### ISSUE TITLE
1.8.9-Crash w/ Dense Ores Mod v2.0.0

### ISSUE THREAD

**Issue by WenXin20** [oitsjustjose/V-Tweaks#8]
Crashes when right-clicking a sparse ore from Denseores Mod v2.0.0.
Turning Easy Crop Harvesting to false fixes it.

Crash Log:
http://pastebin.com/zAHVJ1VS

**Comment by oitsjustjose** [comment]
That's..quite an interesting bug. I'll look into a fix shortly, I've also got to remove some of the reflection code I tried doing to fix compatibility again, so hopefully there'll be an update today or tomorrow (sorry, I'd be quicker but I've been working off of my shitty MacBook Air while on vacation)

**Comment by oitsjustjose** [comment]
Oh! I see why that bug exists. I'm initializing a variable with information before checking to see if it's even a crop. I'll move these initializations to _after_ I've confirmed that the block is a crop, that should prevent this crash... that is, **if I can get my dev environment to work** :|

Having only 4GB of RAM is keeping my development environment from even getting set up, so it might have to wait until this weekend when I'm on a computer that is more useful than a hot-plate.

**Comment by WenXin20** [comment]
Cool, thanks for working on it.
