### ISSUE TITLE
Even with Pet Armoury off, Wolves still attempt to pick up items

### ISSUE THREAD

**Issue by IdrisQe** [oitsjustjose/V-Tweaks#82]
3.4.1.1 for 1.16.5; Pet armoury is turned off, yet tamed wolves keep trying to pick up any item I throw near them, and not even just weapons- **any** item. They repeatedly, nearly every frame, pick up and drop whatever item I throw at them. I've confirmed this issue does not occur with V-Tweaks removed.

**Comment by oitsjustjose** [comment]
Fixed, new release should be out today :)
