### ISSUE TITLE
Modded Challenger Mob Loot Items Not Dropping / Loading as Air

### ISSUE THREAD

**Issue by Jackiecrazy** [oitsjustjose/V-Tweaks#83]
I quadruple checked all my item names, and they are indeed correct, but there are challengers that just don't drop anything special. It's driving me a little mad. A warning message that tells you which entries are invalid would be very helpful.

**Comment by oitsjustjose** [comment]
Actually I've been facing this issue too, it's probably a bug. I'll be looking into it today :smile:

**Comment by oitsjustjose** [comment]
Would you be willing to give this beta a try? It adds debugging statements to print out any issues or successes with loading in Challenger loot.

https://www.mediafire.com/file/i6q9axccefzbvec/VTweaks-1.16.4-3.4.2-BETA.jar/file

**Comment by Jackiecrazy** [comment]
hm. All my entries are being added, but...
```
...
[01:30:03] [modloading-worker-7/INFO] [co.oi.vt.VTweaks/]: Added 0 air to Challenger Mobs Loot
01:30:03.829
game
[01:30:03] [modloading-worker-7/INFO] [co.oi.vt.VTweaks/]: Added 0 air to Challenger Mobs Loot
01:30:21.698
game
[01:30:21] [modloading-worker-6/INFO] [co.oi.vt.VTweaks/]: Added 1 diamond to Challenger Mobs Loot
01:30:21.710
game
[01:30:21] [modloading-worker-6/INFO] [co.oi.vt.VTweaks/]: Added 1 emerald to Challenger Mobs Loot
01:30:21.710
game
[01:30:21] [modloading-worker-6/INFO] [co.oi.vt.VTweaks/]: Added 1 ghast_tear to Challenger Mobs Loot
01:30:21.710
game
[01:30:21] [modloading-worker-6/INFO] [co.oi.vt.VTweaks/]: Added 1 ender_pearl to Challenger Mobs Loot
...
```
Where'd all the air entries come from?

**Comment by oitsjustjose** [comment]
Not sure. What is your config entry for the loot?

**Comment by Jackiecrazy** [comment]
```
challengerMobsLoot = ["minecraft:diamond", "minecraft:emerald", "minecraft:ghast_tear", "minecraft:ender_pearl", "minecraft:emerald", "riskofrainmod:bustling_fungus", "riskofrainmod:crowbar", "riskofrainmod:goat_hoof", "riskofrainmod:lens_makers_glasses", "riskofrainmod:soldiers_syringe", "riskofrainmod:topaz_brooch", "riskofrainmod:tougher_times", "riskofrainmod:infusion", "riskofrainmod:rose_buckler", "majruszs_difficulty:tattered_cloth", "majruszs_difficulty:fishing_treasure_bag", "tombstone:grave_dust", "evilcraft:dark_gem", "evilcraft:condensed_blood*16", "iceandfire:witherbone", "iceandfire:dragonsteel_fire_ingot", "iceandfire:dragonsteel_ice_ingot", "iceandfire:dragonsteel_lightning_ingot", "bloodmagic:defaultcrystal", "bloodmagic:corrosivecrystal", "bloodmagic:vengefulcrystal", "bloodmagic:steadfastcrystal", "bloodmagic:destructivecrystal", "iceandfire:manuscript", "waystones:warp_scroll", "quark:diamond_heart", "apotheosis:boss_summoner", "charm:netherite_nugget"]
```
I know for a fact that these all exist, are registered properly, and (sometimes) drop.

**Comment by oitsjustjose** [comment]
Definitely sounds like a loading order issue. Let me see if there's a way to load this config in when joining a world/server rather than on game load.

**Comment by Jackiecrazy** [comment]
Interesting; I also use items in my config file, and those load correctly. They're also dynamically reloaded in-game, which is probably some forge black magic.

**Comment by oitsjustjose** [comment]
Quite possibly, yeah. Here's a better solution -- it loads in the loot table almost like a datapack, but not quite. That should resolve mod loading priority issues.

Try this

https://www.mediafire.com/file/i6q9axccefzbvec/VTweaks-1.16.4-3.4.2-BETA.jar/file

**Comment by Jackiecrazy** [comment]
It works now, but I am being rendered at roughly half my size. Is this intended?

**Comment by oitsjustjose** [comment]
Hahaha I just fixed that - I was in the middle of a few other features as well when I made that build 😛 

Thanks for testing and confirming. I'll have this fix published today :)
