### ISSUE TITLE
StackOverflowError in large forests with lumbering enchant

### ISSUE THREAD

**Issue by KalleStruik** [oitsjustjose/V-Tweaks#86]
When using lumbering in a large forest it can cause the server to crash. It seems like it is caused by a StackOverflowError from the recursive method calls in `EnchantmentLumberingHandler.java`.

Crash report: https://gist.github.com/KalleStruik/a52b3a6491dea860a6ea885ab83b7065

**Comment by oitsjustjose** [comment]
Fixed in 9792fcc, should be out later today :)
