### ISSUE TITLE
Small Bees option does not disable from config

### ISSUE THREAD

**Issue by czbuendel** [oitsjustjose/V-Tweaks#87]
Setting enableSmallBees to false in vtweaks-common.toml does not disable. Bees stay at half the size.

**Comment by oitsjustjose** [comment]
If I recall correctly this option has been moved to the `client` file.

**Comment by czbuendel** [comment]
I see no options in vtweaks-client.toml for the bees, just sounds and challenger mob particles.

**Comment by czbuendel** [comment]
https://github.com/oitsjustjose/V-Tweaks/blob/fc9b2bbde3a26d57d9ed204200408a92e4bafe15/src/main/java/com/oitsjustjose/vtweaks/common/config/MobTweakConfig.java#L41

**Comment by czbuendel** [comment]
I do see on the client side where the small bee change is made though.
https://github.com/oitsjustjose/V-Tweaks/blob/1.16/src/main/java/com/oitsjustjose/vtweaks/client/SmallBees.java

**Comment by oitsjustjose** [comment]
I just fixed this in acf6d05 -- this should be released later today
