### ISSUE TITLE
Imperishable can be applied with itself

### ISSUE THREAD

**Issue by Jackiecrazy** [oitsjustjose/V-Tweaks#88]
It's a little jarring to find two identical enchantments on an item.

**Comment by oitsjustjose** [comment]
Are you using any other mods?

**Comment by Jackiecrazy** [comment]
Apotheosis and Champions to drop random enchanted items. What I'm seeing is that `canApplyTogether(Enchantment ench)` has been overwritten to just return true, when in vanilla it returns `this!=ench`. Is the overriding intentional?

**Comment by oitsjustjose** [comment]
Fixed in 6e1a1eb, but Apotheosis also will ignore this from time to time, just so you know!
