### ISSUE TITLE
Door placement causing client-side crash

### ISSUE THREAD

**Issue by oitsjustjose** [oitsjustjose/V-Tweaks#9]

**Comment by sdaddy** [comment]
I don't think this is fixed. Was testing out in single player before updating my server and got this crash when placing a door: http://pastebin.com/raw/eq7ivMgj

**Comment by oitsjustjose** [comment]
Fixed this again by removing it. Forgot that while it works in my dev environment, it doesn't work outside of it because the field it looks for has been renamed (thanks to obfuscation).

Decided that removing it was better than making V-Tweaks a core mod just for a silly sound.

**Comment by oitsjustjose** [comment]
I've just uploaded a hotfixed version on CurseForge :)
