### ISSUE TITLE
"disablePetFriendlyFire" also makes certain mod mobs invincible when set to "ALL" (otherwise useful for servers)

### ISSUE THREAD

**Issue by Reshirou** [oitsjustjose/V-Tweaks#90]
Mobs like Ice and Fire's Cockatrice, or Wyrmroost's Butterfly Leviathan are totally invincible with that tweak, which makes it more or less unusable

It seems to have to do with the fact that these mobs are neutral to villagers but attack players on sight (they have green healthbars in ToroHealth)

**Comment by oitsjustjose** [comment]
Is this still an issue? I've fixed a handful of issues around this as of late.

**Comment by oitsjustjose** [comment]
Closing as bug is stale - reopen if needed :)

**Comment by GermanPlasma** [comment]
Yes this is still an issue. I tried attacking the rats in the RATS mod as well as any bird from the mod EXOTICBIRDS and both do not get damage with this option set to ALL.
