### ISSUE TITLE
[Suggestion] Config to disable Challenger Mobs from spawning from Spawner Blocks

### ISSUE THREAD

**Issue by Maxzilla60** [oitsjustjose/V-Tweaks#91]
I love the idea of Challenger Mobs but having them spawn from Spawners makes it way too easy to get plenty of the rare loot they drop by setting up a simple spawner farm.

I suggest a way to make it so Challenger Mobs only spawn naturally and not from Spawner Blocks. Preferably configurable?

**Comment by oitsjustjose** [comment]
I think right now this won't be configurable because of the means by which the event is triggered. I hope that isn't to much of a deal breaker!
