### ISSUE TITLE
An issue or two related to challengers, also a suggestion to them.

### ISSUE THREAD

**Issue by Darkmega18** [oitsjustjose/V-Tweaks#92]
Challenger mobs seem to override the HP and settings of the mob when they spawn. If I happen to get an Atum pharaoh challenger for example out of a spawn egg when stuffing around, even when he's mighty, he'll only have like 60 health or less sometimes, rather than the 150 he's meant to have. While rangers just get absolutely smoked in a hit or two. :V 

Are you meant to be adding this health on or making it a multiplier perhaps? 

---

The suggestion is can you make challengers configurable via jsons and ability to add new "themes" for challengers where you have each one in a separate json in a folder, then if you add new jsons it can pull their stats also.

Settings within could be items they hold and the nbt. Health multipliers or additions. potion effects. RGB of particle effects. base armor on top of gear. number of item drops from them. Then a weight that the challenger will get chosen.

double suggestion, cross compat with champions or apotheosis, to have challengers who can compound into apothic or champion buffed bosses. Champions if you fiddle with this together could alternatively make it so champions can spawn with challenger addons also.

I wanna make juggernauts (netherite gear) and other stuff or silly combos like ninjas (speed and some dark gear and a katana) or reapers (ghostly gear a scythe and transparent effect of corail tombstones etc). :P

**Comment by oitsjustjose** [comment]
This was basically handled in the rewrite I implemented a few months ago so I'm closing this! Thank you by the way! [Here is the changelog where the feature was introduced](https://github.com/oitsjustjose/V-Tweaks/blob/1.16/changelog.md), and [here](https://github.com/oitsjustjose/V-Tweaks/tree/1.18.2/src/main/resources/data/vtweaks/challenger_mobs) is where the datapack data is stored!

**Comment by Darkmega18** [comment]
quite spicy indeed. Thanks.  :D
