### ISSUE TITLE
Seems to crash without JEI after update

### ISSUE THREAD

**Issue by XBagon** [oitsjustjose/V-Tweaks#99]
I updated all the mods of my custom mod pack and then it started crashing when trying to load a world. It seems to relate to V-Tweaks trying to access JEI, which I haven't had installed. I added JEI to confirm and now it works again.
https://crashy.net/uuSgBJsTbPt1hQXLp6Fn

**Comment by oitsjustjose** [comment]
I just put out an update to V-Tweaks yesterday to resolve this, have you tried that update?

**Comment by XBagon** [comment]
I got the newest version on CurseForge - 3.6.5.1, right?

**Comment by oitsjustjose** [comment]
Seems curse's API didn't register my update. Fix coming shortly, thanks for the report :)

**Comment by XBagon** [comment]
new update works :)

**Comment by xXMolgadoGamer01Xx** [comment]
Hi, sorry for open this thread again but I'm having the same crash on V-Tweaks 4.0.7
https://mclo.gs/cTmEGLu

**Comment by oitsjustjose** [comment]
Yeah, as of now it is a hard requirement - I need to change that in the CurseForge download page - I had changed it on Modrinth but forgot to update CF :)
